IF DB_ID('SPOR_ARSIVI') IS NOT NULL
BEGIN 
ALTER DATABASE SPOR_ARSIVI SET SINGLE_USER WITH ROLLBACK IMMEDIATE
Use master 
DROP DATABASE SPOR_ARSIVI
END
GO



CREATE DATABASE SPOR_ARSIVI ON PRIMARY 
(
NAME ='SPOR_ARSIVIDB',
FILENAME = 'c:\database\SPOR_ARSIVI_DB.mdf',
SIZE = 3 MB,
MAXSIZE = 10MB,
FILEGROWTH = 50%
)

LOG ON 
(
 NAME= 'SPOR_ARSIVI_LOG',
 FILENAME='c:\database\SPOR_ARSIVI_LOG.ldf',
 SIZE = 2 MB,
 MAXSIZE = 5 MB,
 FILEGROWTH = 50%
)

GO

USE SPOR_ARSIVI


CREATE TABLE ULKELER (


UlkeID CHAR(3) PRIMARY KEY ,
UlkeAdý VARCHAR(16) NOT NULL

)

GO 
CREATE TABLE SEHIR(
 
Plaka INT IDENTITY(1,1) PRIMARY KEY , 
Sehýr_Adý VARCHAR (20) NOT NULL ,
Ulke_Adý CHAR(3) FOREIGN KEY REFERENCES ULKELER(UlkeID)

)

GO
CREATE TABLE TAKIM(

Takým_ID INT IDENTITY(1,1) PRIMARY KEY ,
Takým_Adý VARCHAR(50) NOT NULL ,
Kurulus_Tarýhý DATE NOT NULL ,
Plaka_shr INT FOREIGN KEY REFERENCES SEHIR(Plaka)
 
 )

 GO
 Create Table STADYUM
(
StadyumID int Identity(1,1) Primary Key,
StadyumAdi Varchar(40) Unique NOT NULL,
Kapasite int NOT NULL,
TakimID int FOREIGN KEY REFERENCES TAKIM(Takým_ID),
Plaka INT FOREIGN KEY REFERENCES SEHIR(Plaka),
    
)
GO
CREATE TABLE OLAYTURU(
 
 Olay_id INT IDENTITY(1,1) PRIMARY KEY , 
 Ad VARCHAR(50) NOT NULL,

 )

 GO

CREATE TABLE HAKEM (

HakemID INT IDENTITY(1,1) PRIMARY KEY ,
UlkeID CHAR (3) FOREIGN KEY REFERENCES ULKELER(UlkeID),
AdSoyad VARCHAR(50) NOT NULL,
Rütbe VARCHAR(18)  

)

GO

CREATE TABLE SEZON (

SezonID INT Identity(1,1) PRIMARY KEY ,
SezonAdý VARCHAR(20) ,
BitiþTarihi DATE  NOT NULL,
BaþlangýcTarihi DATE,
SampýyonID INT FOREIGN KEY REFERENCES TAKIM(Takým_ID),

)

GO
Create Table OYUNCU
(
OyuncuID INT Identity(1,1) Primary Key,
OyuncuAdi Varchar(20)  NOT NULL,
OyuncuSoyadi Varchar(20) NOT NULL,
DogumTarihi DATE NOT NULL,
FormaNumarasi int NOT NULL,
UlkeID CHAR(3) FOREIGN KEY REFERENCES ULKELER(UlkeID),
    
)
GO
CREATE TABLE MAC (
 
 MacID int IDENTITY(1,1) PRIMARY KEY ,
 Mac_Tarihi DATETIME NOT NULL,
 Sezon_id int FOREIGN KEY REFERENCES SEZON(SezonID) ,
 GolS_Misafir INT DEFAULT NULL ,
 GolS_Evsahibi INT DEFAULT NULL ,
 TakýmMID INT FOREIGN KEY REFERENCES TAKIM(Takým_ID) ,
 TakýmEID INT FOREIGN KEY REFERENCES TAKIM(Takým_ID) ,
 StadyumID INT FOREIGN KEY REFERENCES STADYUM(StadyumID) ,


 )

 GO
 CREATE TABLE YONETIR (

Hakem_ID INT FOREIGN KEY REFERENCES HAKEM(HakemID)  ,
MacID  INT FOREIGN KEY REFERENCES MAC(MacID)

)

GO
Create Table MACOLAYI
(
OlayID INT Identity(1,1) Primary Key,
OLayDk Time NOT NULL,
OlayTuruID int FOREIGN KEY REFERENCES OLAYTURU(Olay_id),
Oyuncu1ID int FOREIGN KEY REFERENCES Oyuncu(OyuncuID) NOT NULL,
Oyuncu2ID int FOREIGN KEY REFERENCES Oyuncu(OyuncuID) NULL ,
MacID int FOREIGN KEY REFERENCES MAC(MacID),
)
GO
CREATE TABLE Pozisyon (
PozisyonID INT IDENTITY(1,1) PRIMARY KEY ,
PozisyonAdý VARCHAR (20),
--SözleþmeID INT FOREIGN KEY REFERENCES SOZLESME(SözleþmeID) 
)
GO
CREATE TABLE SOZLESME(
SözleþmeID INT IDENTITY(1,1) PRIMARY KEY , 
SözleþmeBaþT DATE NOT NULL,
SözleþmeBitT DATE NULL ,
YýllýkÜcret MONEY NOT NULL,
Pozisyon_ID INT FOREIGN KEY REFERENCES Pozisyon(PozisyonID), 
Oyuncu_ID INT FOREIGN KEY REFERENCES Oyuncu(OyuncuID), 
)
GO

CREATE TABLE Sponsor(
SponsorID INT IDENTITY (1,1) PRIMARY KEY , 
SponsorAdý VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE SponsorOlur(
Takým_ID INT FOREIGN KEY REFERENCES Takým(Takým_ID), 
SponsorID INT FOREIGN KEY REFERENCES Sponsor(SponsorID), 
SözleþmeBaþT DATE NOT NULL,
SözleþmeBitT DATE NULL,
YýllýFiyat MONEY NOT NULL,

)
GO
Create Table SOZLESMEYAPAR
(
SozlesmeID int FOREIGN KEY REFERENCES SOZLESME(SözleþmeID),
TakimID int FOREIGN KEY REFERENCES TAKIM(Takým_ID),
)
GO
CREATE TABLE TAKIMSEZONDAOYNAR (

Takým_ID INT FOREIGN KEY REFERENCES TAKIM(Takým_ID),
Sezon_ID INT FOREIGN KEY REFERENCES SEZON(SezonID) ,
AttýðýGol INT NOT NULL,
YediðiGol INT NOT NULL ,
Averaj INT NOT NULL,
Galibiyet INT NOT NULL,
Malubiyet INT NOT NULL, 
Berabere INT NOT NULL ,
Puan INT NOT NULL

)

GO